# Prometheus configuration for CCany monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # CCany application metrics
  - job_name: "ccany"
    static_configs:
      - targets: ["ccany:8082"]
    metrics_path: '/health/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http

  # CCany health endpoints
  - job_name: "ccany-health"
    static_configs:
      - targets: ["ccany:8082"]
    metrics_path: '/health'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: http

  # Redis metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s

  # Node exporter for system metrics (if needed)
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"